server:
  port: 9000

spring:
  application:
    name: gin-gateway
  cloud:
    gateway:
      routes:
      - id: api-route
        # lb\u4EE3\u8868\u4ECE\u6CE8\u518C\u4E2D\u5FC3\u83B7\u53D6\u670D\u52A1
        uri: lb://api-service
        predicates:
        # \u8F6C\u53D1\u8BE5\u8DEF\u5F84
        - Path=/api/**
#        filters:
#        # \u662F\u5426\u53BB\u6389\u524D\u7F00\uFF08\u7B2C\u4E00\u4E2A\u76EE\u5F55\uFF09
#        - StripPrefix=1
      - id: h5-route
        # lb\u4EE3\u8868\u4ECE\u6CE8\u518C\u4E2D\u5FC3\u83B7\u53D6\u670D\u52A1
        uri: lb://h5-service
        predicates:
        # \u8F6C\u53D1\u8BE5\u8DEF\u5F84
        - Path=/h5/**
    zookeeper:
      connect-string: 114.55.58.53:2181 #zk\u96C6\u7FA4\u4E3B\u673A\uFF0C\u591A\u4E2A\u7528\u9017\u53F7\u9694\u5F00
      discovery:
        enabled: true
        register: true